version: '3'

services:
  frontend:
    container_name: nsll-frontend-prod
    image: nsll-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '3000:3000'
