version: '3'

services:
  frontend:
    container_name: nsll-frontend-dev
    image: nsll-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
